import Head from 'next/head'
import Navbar from './components/navbar'
import styles from '@/styles/Home.module.css'

const Home = ({ posts }) => {
  return (
    <>
      <Head>
        <title>Gilang Eka Pratama</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={`${styles.main} ${styles.center}`}>
        <h1>Hi!</h1>
        <h1>My name is Gilang Eka Pratama</h1>
      </main>
      {posts.map((post) => (
        <div key={post.id}>
          <h2>{post.title}</h2>
        </div>
      ))}
    </>
  )
}

export default Home

export const getStaticProps = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts");
  const data = await res.json();

  return {
    props: {
      posts: data,
    },
  };
};
